
package stratego2.view.gui;

import stratego2.model.Color;

/**
 *
 * @author roussew
 */
public class GameSquare extends javax.swing.JPanel {
    boolean isActive;
    int row;
    int column;
    /**
     * Creates new form GameSquare
     */
    public GameSquare(boolean isActive) {
        this.isActive = isActive;
        initComponents();
        setColor();
    }

    public GameSquare(boolean isActive, int row, int column) {
        this.isActive = isActive;
        this.row = row;
        this.column = column;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(50, 50));
        setRequestFocusEnabled(false);
        setSize(new java.awt.Dimension(50, 50));

        jLabel1.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * sets color based on whether or not the square is dead. 
     */
    private void setColor() {
        if(isActive) this.setBackground(java.awt.Color.white);
        else this.setBackground(java.awt.Color.lightGray);
    }
}
