
package stratego2.view.gui;

/**
 *
 * @author roussew
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gameSquare14 = new stratego2.view.gui.GameSquare();
        gameSquare16 = new stratego2.view.gui.GameSquare(true, 0, 1);
        gameSquare17 = new stratego2.view.gui.GameSquare(true, 0, 2);
        gameSquare18 = new stratego2.view.gui.GameSquare(true, 0 3);
        gameSquare19 = new stratego2.view.gui.GameSquare(true, 0, 4);
        gameSquare20 = new stratego2.view.gui.GameSquare(true, 0, 5);
        gameSquare21 = new stratego2.view.gui.GameSquare(0,6);
        gameSquare22 = new stratego2.view.gui.GameSquare(0,7);
        gameSquare23 = new stratego2.view.gui.GameSquare(0,8);
        gameSquare24 = new stratego2.view.gui.GameSquare(0,9);
        gameSquare25 = new stratego2.view.gui.GameSquare(1,9);
        gameSquare26 = new stratego2.view.gui.GameSquare(1,8);
        gameSquare27 = new stratego2.view.gui.GameSquare(1,7);
        gameSquare28 = new stratego2.view.gui.GameSquare(1,6);
        gameSquare29 = new stratego2.view.gui.GameSquare(1,5);
        gameSquare30 = new stratego2.view.gui.GameSquare(1,4);
        gameSquare31 = new stratego2.view.gui.GameSquare(1,3);
        gameSquare32 = new stratego2.view.gui.GameSquare(1,2);
        gameSquare33 = new stratego2.view.gui.GameSquare(1,1);
        gameSquare34 = new stratego2.view.gui.GameSquare(1,0);
        gameSquare35 = new stratego2.view.gui.GameSquare(2,0);
        gameSquare36 = new stratego2.view.gui.GameSquare();
        gameSquare37 = new stratego2.view.gui.GameSquare();
        gameSquare38 = new stratego2.view.gui.GameSquare();
        gameSquare39 = new stratego2.view.gui.GameSquare();
        gameSquare40 = new stratego2.view.gui.GameSquare();
        gameSquare41 = new stratego2.view.gui.GameSquare();
        gameSquare42 = new stratego2.view.gui.GameSquare();
        gameSquare43 = new stratego2.view.gui.GameSquare();
        gameSquare44 = new stratego2.view.gui.GameSquare();
        gameSquare45 = new stratego2.view.gui.GameSquare();
        gameSquare46 = new stratego2.view.gui.GameSquare();
        gameSquare47 = new stratego2.view.gui.GameSquare();
        gameSquare48 = new stratego2.view.gui.GameSquare();
        gameSquare49 = new stratego2.view.gui.GameSquare();
        gameSquare50 = new stratego2.view.gui.GameSquare();
        gameSquare51 = new stratego2.view.gui.GameSquare();
        gameSquare52 = new stratego2.view.gui.GameSquare();
        gameSquare53 = new stratego2.view.gui.GameSquare();
        gameSquare54 = new stratego2.view.gui.GameSquare();
        gameSquare55 = new stratego2.view.gui.GameSquare();
        gameSquare56 = new stratego2.view.gui.GameSquare();
        gameSquare57 = new stratego2.view.gui.GameSquare();
        gameSquare58 = new stratego2.view.gui.GameSquare();
        gameSquare59 = new stratego2.view.gui.GameSquare();
        gameSquare60 = new stratego2.view.gui.GameSquare();
        gameSquare61 = new stratego2.view.gui.GameSquare();
        gameSquare62 = new stratego2.view.gui.GameSquare();
        gameSquare63 = new stratego2.view.gui.GameSquare();
        gameSquare64 = new stratego2.view.gui.GameSquare();
        gameSquare65 = new stratego2.view.gui.GameSquare();
        gameSquare66 = new stratego2.view.gui.GameSquare();
        gameSquare67 = new stratego2.view.gui.GameSquare();
        gameSquare68 = new stratego2.view.gui.GameSquare();
        gameSquare69 = new stratego2.view.gui.GameSquare();
        gameSquare70 = new stratego2.view.gui.GameSquare();
        gameSquare71 = new stratego2.view.gui.GameSquare();
        gameSquare72 = new stratego2.view.gui.GameSquare();
        gameSquare73 = new stratego2.view.gui.GameSquare();
        gameSquare74 = new stratego2.view.gui.GameSquare();
        gameSquare75 = new stratego2.view.gui.GameSquare();
        gameSquare76 = new stratego2.view.gui.GameSquare();
        gameSquare77 = new stratego2.view.gui.GameSquare();
        gameSquare78 = new stratego2.view.gui.GameSquare();
        gameSquare79 = new stratego2.view.gui.GameSquare();
        gameSquare80 = new stratego2.view.gui.GameSquare();
        gameSquare81 = new stratego2.view.gui.GameSquare();
        gameSquare82 = new stratego2.view.gui.GameSquare();
        gameSquare83 = new stratego2.view.gui.GameSquare();
        gameSquare84 = new stratego2.view.gui.GameSquare();
        gameSquare85 = new stratego2.view.gui.GameSquare();
        gameSquare86 = new stratego2.view.gui.GameSquare();
        gameSquare87 = new stratego2.view.gui.GameSquare();
        gameSquare88 = new stratego2.view.gui.GameSquare();
        gameSquare89 = new stratego2.view.gui.GameSquare();
        gameSquare90 = new stratego2.view.gui.GameSquare();
        gameSquare91 = new stratego2.view.gui.GameSquare();
        gameSquare92 = new stratego2.view.gui.GameSquare();
        gameSquare93 = new stratego2.view.gui.GameSquare();
        gameSquare94 = new stratego2.view.gui.GameSquare();
        gameSquare95 = new stratego2.view.gui.GameSquare();
        gameSquare96 = new stratego2.view.gui.GameSquare();
        gameSquare97 = new stratego2.view.gui.GameSquare();
        gameSquare98 = new stratego2.view.gui.GameSquare();
        gameSquare99 = new stratego2.view.gui.GameSquare();
        gameSquare100 = new stratego2.view.gui.GameSquare();
        gameSquare101 = new stratego2.view.gui.GameSquare();
        gameSquare102 = new stratego2.view.gui.GameSquare();
        gameSquare103 = new stratego2.view.gui.GameSquare();
        gameSquare104 = new stratego2.view.gui.GameSquare();
        gameSquare105 = new stratego2.view.gui.GameSquare();
        gameSquare106 = new stratego2.view.gui.GameSquare();
        gameSquare107 = new stratego2.view.gui.GameSquare();
        gameSquare108 = new stratego2.view.gui.GameSquare();
        gameSquare109 = new stratego2.view.gui.GameSquare();
        gameSquare110 = new stratego2.view.gui.GameSquare();
        gameSquare111 = new stratego2.view.gui.GameSquare();
        gameSquare112 = new stratego2.view.gui.GameSquare();
        gameSquare113 = new stratego2.view.gui.GameSquare();
        gameSquare15 = new stratego2.view.gui.GameSquare(true, 0, 0);
        gameSquare1 = new stratego2.view.gui.GameSquare();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameSquare14.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare14Layout = new javax.swing.GroupLayout(gameSquare14);
        gameSquare14.setLayout(gameSquare14Layout);
        gameSquare14Layout.setHorizontalGroup(
            gameSquare14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare14Layout.setVerticalGroup(
            gameSquare14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        gameSquare16.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare16Layout = new javax.swing.GroupLayout(gameSquare16);
        gameSquare16.setLayout(gameSquare16Layout);
        gameSquare16Layout.setHorizontalGroup(
            gameSquare16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare16Layout.setVerticalGroup(
            gameSquare16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        gameSquare17.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare17Layout = new javax.swing.GroupLayout(gameSquare17);
        gameSquare17.setLayout(gameSquare17Layout);
        gameSquare17Layout.setHorizontalGroup(
            gameSquare17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare17Layout.setVerticalGroup(
            gameSquare17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        gameSquare18.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare18Layout = new javax.swing.GroupLayout(gameSquare18);
        gameSquare18.setLayout(gameSquare18Layout);
        gameSquare18Layout.setHorizontalGroup(
            gameSquare18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare18Layout.setVerticalGroup(
            gameSquare18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        gameSquare19.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare19Layout = new javax.swing.GroupLayout(gameSquare19);
        gameSquare19.setLayout(gameSquare19Layout);
        gameSquare19Layout.setHorizontalGroup(
            gameSquare19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare19Layout.setVerticalGroup(
            gameSquare19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        gameSquare20.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare20Layout = new javax.swing.GroupLayout(gameSquare20);
        gameSquare20.setLayout(gameSquare20Layout);
        gameSquare20Layout.setHorizontalGroup(
            gameSquare20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare20Layout.setVerticalGroup(
            gameSquare20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        gameSquare21.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare21Layout = new javax.swing.GroupLayout(gameSquare21);
        gameSquare21.setLayout(gameSquare21Layout);
        gameSquare21Layout.setHorizontalGroup(
            gameSquare21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare21Layout.setVerticalGroup(
            gameSquare21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        gameSquare22.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare22Layout = new javax.swing.GroupLayout(gameSquare22);
        gameSquare22.setLayout(gameSquare22Layout);
        gameSquare22Layout.setHorizontalGroup(
            gameSquare22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare22Layout.setVerticalGroup(
            gameSquare22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        gameSquare23.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare23Layout = new javax.swing.GroupLayout(gameSquare23);
        gameSquare23.setLayout(gameSquare23Layout);
        gameSquare23Layout.setHorizontalGroup(
            gameSquare23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare23Layout.setVerticalGroup(
            gameSquare23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        gameSquare24.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare24Layout = new javax.swing.GroupLayout(gameSquare24);
        gameSquare24.setLayout(gameSquare24Layout);
        gameSquare24Layout.setHorizontalGroup(
            gameSquare24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare24Layout.setVerticalGroup(
            gameSquare24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        gameSquare25.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare25Layout = new javax.swing.GroupLayout(gameSquare25);
        gameSquare25.setLayout(gameSquare25Layout);
        gameSquare25Layout.setHorizontalGroup(
            gameSquare25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare25Layout.setVerticalGroup(
            gameSquare25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        gameSquare26.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare26Layout = new javax.swing.GroupLayout(gameSquare26);
        gameSquare26.setLayout(gameSquare26Layout);
        gameSquare26Layout.setHorizontalGroup(
            gameSquare26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare26Layout.setVerticalGroup(
            gameSquare26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        gameSquare27.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare27Layout = new javax.swing.GroupLayout(gameSquare27);
        gameSquare27.setLayout(gameSquare27Layout);
        gameSquare27Layout.setHorizontalGroup(
            gameSquare27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare27Layout.setVerticalGroup(
            gameSquare27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        gameSquare28.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare28Layout = new javax.swing.GroupLayout(gameSquare28);
        gameSquare28.setLayout(gameSquare28Layout);
        gameSquare28Layout.setHorizontalGroup(
            gameSquare28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare28Layout.setVerticalGroup(
            gameSquare28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        gameSquare29.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare29Layout = new javax.swing.GroupLayout(gameSquare29);
        gameSquare29.setLayout(gameSquare29Layout);
        gameSquare29Layout.setHorizontalGroup(
            gameSquare29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare29Layout.setVerticalGroup(
            gameSquare29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        gameSquare30.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare30Layout = new javax.swing.GroupLayout(gameSquare30);
        gameSquare30.setLayout(gameSquare30Layout);
        gameSquare30Layout.setHorizontalGroup(
            gameSquare30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare30Layout.setVerticalGroup(
            gameSquare30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        gameSquare31.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare31Layout = new javax.swing.GroupLayout(gameSquare31);
        gameSquare31.setLayout(gameSquare31Layout);
        gameSquare31Layout.setHorizontalGroup(
            gameSquare31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare31Layout.setVerticalGroup(
            gameSquare31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        gameSquare32.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare32Layout = new javax.swing.GroupLayout(gameSquare32);
        gameSquare32.setLayout(gameSquare32Layout);
        gameSquare32Layout.setHorizontalGroup(
            gameSquare32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare32Layout.setVerticalGroup(
            gameSquare32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        gameSquare33.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare33Layout = new javax.swing.GroupLayout(gameSquare33);
        gameSquare33.setLayout(gameSquare33Layout);
        gameSquare33Layout.setHorizontalGroup(
            gameSquare33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare33Layout.setVerticalGroup(
            gameSquare33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        gameSquare34.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare34Layout = new javax.swing.GroupLayout(gameSquare34);
        gameSquare34.setLayout(gameSquare34Layout);
        gameSquare34Layout.setHorizontalGroup(
            gameSquare34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare34Layout.setVerticalGroup(
            gameSquare34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        gameSquare35.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare35Layout = new javax.swing.GroupLayout(gameSquare35);
        gameSquare35.setLayout(gameSquare35Layout);
        gameSquare35Layout.setHorizontalGroup(
            gameSquare35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare35Layout.setVerticalGroup(
            gameSquare35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        gameSquare36.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare36Layout = new javax.swing.GroupLayout(gameSquare36);
        gameSquare36.setLayout(gameSquare36Layout);
        gameSquare36Layout.setHorizontalGroup(
            gameSquare36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare36Layout.setVerticalGroup(
            gameSquare36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        gameSquare37.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare37Layout = new javax.swing.GroupLayout(gameSquare37);
        gameSquare37.setLayout(gameSquare37Layout);
        gameSquare37Layout.setHorizontalGroup(
            gameSquare37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare37Layout.setVerticalGroup(
            gameSquare37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        gameSquare38.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare38Layout = new javax.swing.GroupLayout(gameSquare38);
        gameSquare38.setLayout(gameSquare38Layout);
        gameSquare38Layout.setHorizontalGroup(
            gameSquare38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare38Layout.setVerticalGroup(
            gameSquare38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare38, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        gameSquare39.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare39Layout = new javax.swing.GroupLayout(gameSquare39);
        gameSquare39.setLayout(gameSquare39Layout);
        gameSquare39Layout.setHorizontalGroup(
            gameSquare39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare39Layout.setVerticalGroup(
            gameSquare39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare39, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        gameSquare40.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare40Layout = new javax.swing.GroupLayout(gameSquare40);
        gameSquare40.setLayout(gameSquare40Layout);
        gameSquare40Layout.setHorizontalGroup(
            gameSquare40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare40Layout.setVerticalGroup(
            gameSquare40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        gameSquare41.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare41Layout = new javax.swing.GroupLayout(gameSquare41);
        gameSquare41.setLayout(gameSquare41Layout);
        gameSquare41Layout.setHorizontalGroup(
            gameSquare41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare41Layout.setVerticalGroup(
            gameSquare41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare41, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        gameSquare42.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare42Layout = new javax.swing.GroupLayout(gameSquare42);
        gameSquare42.setLayout(gameSquare42Layout);
        gameSquare42Layout.setHorizontalGroup(
            gameSquare42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare42Layout.setVerticalGroup(
            gameSquare42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare42, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        gameSquare43.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare43Layout = new javax.swing.GroupLayout(gameSquare43);
        gameSquare43.setLayout(gameSquare43Layout);
        gameSquare43Layout.setHorizontalGroup(
            gameSquare43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare43Layout.setVerticalGroup(
            gameSquare43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        gameSquare44.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare44Layout = new javax.swing.GroupLayout(gameSquare44);
        gameSquare44.setLayout(gameSquare44Layout);
        gameSquare44Layout.setHorizontalGroup(
            gameSquare44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare44Layout.setVerticalGroup(
            gameSquare44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        gameSquare45.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare45Layout = new javax.swing.GroupLayout(gameSquare45);
        gameSquare45.setLayout(gameSquare45Layout);
        gameSquare45Layout.setHorizontalGroup(
            gameSquare45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare45Layout.setVerticalGroup(
            gameSquare45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare45, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        gameSquare46.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare46Layout = new javax.swing.GroupLayout(gameSquare46);
        gameSquare46.setLayout(gameSquare46Layout);
        gameSquare46Layout.setHorizontalGroup(
            gameSquare46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare46Layout.setVerticalGroup(
            gameSquare46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare46, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        gameSquare47.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare47Layout = new javax.swing.GroupLayout(gameSquare47);
        gameSquare47.setLayout(gameSquare47Layout);
        gameSquare47Layout.setHorizontalGroup(
            gameSquare47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare47Layout.setVerticalGroup(
            gameSquare47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        gameSquare48.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare48Layout = new javax.swing.GroupLayout(gameSquare48);
        gameSquare48.setLayout(gameSquare48Layout);
        gameSquare48Layout.setHorizontalGroup(
            gameSquare48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare48Layout.setVerticalGroup(
            gameSquare48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare48, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        gameSquare49.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare49Layout = new javax.swing.GroupLayout(gameSquare49);
        gameSquare49.setLayout(gameSquare49Layout);
        gameSquare49Layout.setHorizontalGroup(
            gameSquare49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare49Layout.setVerticalGroup(
            gameSquare49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare49, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        gameSquare50.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare50Layout = new javax.swing.GroupLayout(gameSquare50);
        gameSquare50.setLayout(gameSquare50Layout);
        gameSquare50Layout.setHorizontalGroup(
            gameSquare50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare50Layout.setVerticalGroup(
            gameSquare50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare50, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        gameSquare51.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare51Layout = new javax.swing.GroupLayout(gameSquare51);
        gameSquare51.setLayout(gameSquare51Layout);
        gameSquare51Layout.setHorizontalGroup(
            gameSquare51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare51Layout.setVerticalGroup(
            gameSquare51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare51, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        gameSquare52.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare52Layout = new javax.swing.GroupLayout(gameSquare52);
        gameSquare52.setLayout(gameSquare52Layout);
        gameSquare52Layout.setHorizontalGroup(
            gameSquare52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare52Layout.setVerticalGroup(
            gameSquare52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare52, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        gameSquare53.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare53Layout = new javax.swing.GroupLayout(gameSquare53);
        gameSquare53.setLayout(gameSquare53Layout);
        gameSquare53Layout.setHorizontalGroup(
            gameSquare53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare53Layout.setVerticalGroup(
            gameSquare53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare53, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        gameSquare54.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare54Layout = new javax.swing.GroupLayout(gameSquare54);
        gameSquare54.setLayout(gameSquare54Layout);
        gameSquare54Layout.setHorizontalGroup(
            gameSquare54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare54Layout.setVerticalGroup(
            gameSquare54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare54, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        gameSquare55.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare55Layout = new javax.swing.GroupLayout(gameSquare55);
        gameSquare55.setLayout(gameSquare55Layout);
        gameSquare55Layout.setHorizontalGroup(
            gameSquare55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare55Layout.setVerticalGroup(
            gameSquare55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare55, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        gameSquare56.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare56Layout = new javax.swing.GroupLayout(gameSquare56);
        gameSquare56.setLayout(gameSquare56Layout);
        gameSquare56Layout.setHorizontalGroup(
            gameSquare56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare56Layout.setVerticalGroup(
            gameSquare56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare56, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        gameSquare57.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare57Layout = new javax.swing.GroupLayout(gameSquare57);
        gameSquare57.setLayout(gameSquare57Layout);
        gameSquare57Layout.setHorizontalGroup(
            gameSquare57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare57Layout.setVerticalGroup(
            gameSquare57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare57, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        gameSquare58.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare58Layout = new javax.swing.GroupLayout(gameSquare58);
        gameSquare58.setLayout(gameSquare58Layout);
        gameSquare58Layout.setHorizontalGroup(
            gameSquare58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare58Layout.setVerticalGroup(
            gameSquare58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare58, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        gameSquare59.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare59Layout = new javax.swing.GroupLayout(gameSquare59);
        gameSquare59.setLayout(gameSquare59Layout);
        gameSquare59Layout.setHorizontalGroup(
            gameSquare59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare59Layout.setVerticalGroup(
            gameSquare59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare59, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        gameSquare60.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare60Layout = new javax.swing.GroupLayout(gameSquare60);
        gameSquare60.setLayout(gameSquare60Layout);
        gameSquare60Layout.setHorizontalGroup(
            gameSquare60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare60Layout.setVerticalGroup(
            gameSquare60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare60, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        gameSquare61.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare61Layout = new javax.swing.GroupLayout(gameSquare61);
        gameSquare61.setLayout(gameSquare61Layout);
        gameSquare61Layout.setHorizontalGroup(
            gameSquare61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare61Layout.setVerticalGroup(
            gameSquare61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare61, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        gameSquare62.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare62Layout = new javax.swing.GroupLayout(gameSquare62);
        gameSquare62.setLayout(gameSquare62Layout);
        gameSquare62Layout.setHorizontalGroup(
            gameSquare62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare62Layout.setVerticalGroup(
            gameSquare62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare62, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        gameSquare63.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare63Layout = new javax.swing.GroupLayout(gameSquare63);
        gameSquare63.setLayout(gameSquare63Layout);
        gameSquare63Layout.setHorizontalGroup(
            gameSquare63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare63Layout.setVerticalGroup(
            gameSquare63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        gameSquare64.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare64Layout = new javax.swing.GroupLayout(gameSquare64);
        gameSquare64.setLayout(gameSquare64Layout);
        gameSquare64Layout.setHorizontalGroup(
            gameSquare64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare64Layout.setVerticalGroup(
            gameSquare64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        gameSquare65.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare65Layout = new javax.swing.GroupLayout(gameSquare65);
        gameSquare65.setLayout(gameSquare65Layout);
        gameSquare65Layout.setHorizontalGroup(
            gameSquare65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare65Layout.setVerticalGroup(
            gameSquare65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare65, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        gameSquare66.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare66Layout = new javax.swing.GroupLayout(gameSquare66);
        gameSquare66.setLayout(gameSquare66Layout);
        gameSquare66Layout.setHorizontalGroup(
            gameSquare66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare66Layout.setVerticalGroup(
            gameSquare66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare66, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        gameSquare67.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare67Layout = new javax.swing.GroupLayout(gameSquare67);
        gameSquare67.setLayout(gameSquare67Layout);
        gameSquare67Layout.setHorizontalGroup(
            gameSquare67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare67Layout.setVerticalGroup(
            gameSquare67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare67, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        gameSquare68.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare68Layout = new javax.swing.GroupLayout(gameSquare68);
        gameSquare68.setLayout(gameSquare68Layout);
        gameSquare68Layout.setHorizontalGroup(
            gameSquare68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare68Layout.setVerticalGroup(
            gameSquare68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare68, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        gameSquare69.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare69Layout = new javax.swing.GroupLayout(gameSquare69);
        gameSquare69.setLayout(gameSquare69Layout);
        gameSquare69Layout.setHorizontalGroup(
            gameSquare69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare69Layout.setVerticalGroup(
            gameSquare69Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare69, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        gameSquare70.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare70Layout = new javax.swing.GroupLayout(gameSquare70);
        gameSquare70.setLayout(gameSquare70Layout);
        gameSquare70Layout.setHorizontalGroup(
            gameSquare70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare70Layout.setVerticalGroup(
            gameSquare70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare70, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        gameSquare71.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare71Layout = new javax.swing.GroupLayout(gameSquare71);
        gameSquare71.setLayout(gameSquare71Layout);
        gameSquare71Layout.setHorizontalGroup(
            gameSquare71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare71Layout.setVerticalGroup(
            gameSquare71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare71, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        gameSquare72.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare72Layout = new javax.swing.GroupLayout(gameSquare72);
        gameSquare72.setLayout(gameSquare72Layout);
        gameSquare72Layout.setHorizontalGroup(
            gameSquare72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare72Layout.setVerticalGroup(
            gameSquare72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare72, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        gameSquare73.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare73Layout = new javax.swing.GroupLayout(gameSquare73);
        gameSquare73.setLayout(gameSquare73Layout);
        gameSquare73Layout.setHorizontalGroup(
            gameSquare73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare73Layout.setVerticalGroup(
            gameSquare73Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare73, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        gameSquare74.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare74Layout = new javax.swing.GroupLayout(gameSquare74);
        gameSquare74.setLayout(gameSquare74Layout);
        gameSquare74Layout.setHorizontalGroup(
            gameSquare74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare74Layout.setVerticalGroup(
            gameSquare74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare74, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        gameSquare75.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare75Layout = new javax.swing.GroupLayout(gameSquare75);
        gameSquare75.setLayout(gameSquare75Layout);
        gameSquare75Layout.setHorizontalGroup(
            gameSquare75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare75Layout.setVerticalGroup(
            gameSquare75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare75, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        gameSquare76.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare76Layout = new javax.swing.GroupLayout(gameSquare76);
        gameSquare76.setLayout(gameSquare76Layout);
        gameSquare76Layout.setHorizontalGroup(
            gameSquare76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare76Layout.setVerticalGroup(
            gameSquare76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare76, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        gameSquare77.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare77Layout = new javax.swing.GroupLayout(gameSquare77);
        gameSquare77.setLayout(gameSquare77Layout);
        gameSquare77Layout.setHorizontalGroup(
            gameSquare77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare77Layout.setVerticalGroup(
            gameSquare77Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare77, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        gameSquare78.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare78Layout = new javax.swing.GroupLayout(gameSquare78);
        gameSquare78.setLayout(gameSquare78Layout);
        gameSquare78Layout.setHorizontalGroup(
            gameSquare78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare78Layout.setVerticalGroup(
            gameSquare78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare78, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        gameSquare79.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare79Layout = new javax.swing.GroupLayout(gameSquare79);
        gameSquare79.setLayout(gameSquare79Layout);
        gameSquare79Layout.setHorizontalGroup(
            gameSquare79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare79Layout.setVerticalGroup(
            gameSquare79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare79, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        gameSquare80.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare80Layout = new javax.swing.GroupLayout(gameSquare80);
        gameSquare80.setLayout(gameSquare80Layout);
        gameSquare80Layout.setHorizontalGroup(
            gameSquare80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare80Layout.setVerticalGroup(
            gameSquare80Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare80, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        gameSquare81.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare81Layout = new javax.swing.GroupLayout(gameSquare81);
        gameSquare81.setLayout(gameSquare81Layout);
        gameSquare81Layout.setHorizontalGroup(
            gameSquare81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare81Layout.setVerticalGroup(
            gameSquare81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare81, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        gameSquare82.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare82Layout = new javax.swing.GroupLayout(gameSquare82);
        gameSquare82.setLayout(gameSquare82Layout);
        gameSquare82Layout.setHorizontalGroup(
            gameSquare82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare82Layout.setVerticalGroup(
            gameSquare82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare82, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        gameSquare83.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare83Layout = new javax.swing.GroupLayout(gameSquare83);
        gameSquare83.setLayout(gameSquare83Layout);
        gameSquare83Layout.setHorizontalGroup(
            gameSquare83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare83Layout.setVerticalGroup(
            gameSquare83Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare83, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        gameSquare84.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare84Layout = new javax.swing.GroupLayout(gameSquare84);
        gameSquare84.setLayout(gameSquare84Layout);
        gameSquare84Layout.setHorizontalGroup(
            gameSquare84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare84Layout.setVerticalGroup(
            gameSquare84Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare84, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        gameSquare85.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare85Layout = new javax.swing.GroupLayout(gameSquare85);
        gameSquare85.setLayout(gameSquare85Layout);
        gameSquare85Layout.setHorizontalGroup(
            gameSquare85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare85Layout.setVerticalGroup(
            gameSquare85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare85, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        gameSquare86.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare86Layout = new javax.swing.GroupLayout(gameSquare86);
        gameSquare86.setLayout(gameSquare86Layout);
        gameSquare86Layout.setHorizontalGroup(
            gameSquare86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare86Layout.setVerticalGroup(
            gameSquare86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare86, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        gameSquare87.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare87Layout = new javax.swing.GroupLayout(gameSquare87);
        gameSquare87.setLayout(gameSquare87Layout);
        gameSquare87Layout.setHorizontalGroup(
            gameSquare87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare87Layout.setVerticalGroup(
            gameSquare87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare87, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        gameSquare88.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare88Layout = new javax.swing.GroupLayout(gameSquare88);
        gameSquare88.setLayout(gameSquare88Layout);
        gameSquare88Layout.setHorizontalGroup(
            gameSquare88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare88Layout.setVerticalGroup(
            gameSquare88Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare88, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        gameSquare89.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare89Layout = new javax.swing.GroupLayout(gameSquare89);
        gameSquare89.setLayout(gameSquare89Layout);
        gameSquare89Layout.setHorizontalGroup(
            gameSquare89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare89Layout.setVerticalGroup(
            gameSquare89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare89, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        gameSquare90.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare90Layout = new javax.swing.GroupLayout(gameSquare90);
        gameSquare90.setLayout(gameSquare90Layout);
        gameSquare90Layout.setHorizontalGroup(
            gameSquare90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare90Layout.setVerticalGroup(
            gameSquare90Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare90, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        gameSquare91.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare91Layout = new javax.swing.GroupLayout(gameSquare91);
        gameSquare91.setLayout(gameSquare91Layout);
        gameSquare91Layout.setHorizontalGroup(
            gameSquare91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare91Layout.setVerticalGroup(
            gameSquare91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare91, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        gameSquare92.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare92Layout = new javax.swing.GroupLayout(gameSquare92);
        gameSquare92.setLayout(gameSquare92Layout);
        gameSquare92Layout.setHorizontalGroup(
            gameSquare92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare92Layout.setVerticalGroup(
            gameSquare92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare92, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        gameSquare93.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare93Layout = new javax.swing.GroupLayout(gameSquare93);
        gameSquare93.setLayout(gameSquare93Layout);
        gameSquare93Layout.setHorizontalGroup(
            gameSquare93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare93Layout.setVerticalGroup(
            gameSquare93Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare93, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        gameSquare94.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare94Layout = new javax.swing.GroupLayout(gameSquare94);
        gameSquare94.setLayout(gameSquare94Layout);
        gameSquare94Layout.setHorizontalGroup(
            gameSquare94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare94Layout.setVerticalGroup(
            gameSquare94Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare94, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        gameSquare95.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare95Layout = new javax.swing.GroupLayout(gameSquare95);
        gameSquare95.setLayout(gameSquare95Layout);
        gameSquare95Layout.setHorizontalGroup(
            gameSquare95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare95Layout.setVerticalGroup(
            gameSquare95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare95, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        gameSquare96.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare96Layout = new javax.swing.GroupLayout(gameSquare96);
        gameSquare96.setLayout(gameSquare96Layout);
        gameSquare96Layout.setHorizontalGroup(
            gameSquare96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare96Layout.setVerticalGroup(
            gameSquare96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare96, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        gameSquare97.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare97Layout = new javax.swing.GroupLayout(gameSquare97);
        gameSquare97.setLayout(gameSquare97Layout);
        gameSquare97Layout.setHorizontalGroup(
            gameSquare97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare97Layout.setVerticalGroup(
            gameSquare97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare97, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        gameSquare98.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare98Layout = new javax.swing.GroupLayout(gameSquare98);
        gameSquare98.setLayout(gameSquare98Layout);
        gameSquare98Layout.setHorizontalGroup(
            gameSquare98Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare98Layout.setVerticalGroup(
            gameSquare98Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare98, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        gameSquare99.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare99Layout = new javax.swing.GroupLayout(gameSquare99);
        gameSquare99.setLayout(gameSquare99Layout);
        gameSquare99Layout.setHorizontalGroup(
            gameSquare99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare99Layout.setVerticalGroup(
            gameSquare99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare99, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        gameSquare100.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare100Layout = new javax.swing.GroupLayout(gameSquare100);
        gameSquare100.setLayout(gameSquare100Layout);
        gameSquare100Layout.setHorizontalGroup(
            gameSquare100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare100Layout.setVerticalGroup(
            gameSquare100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare100, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        gameSquare101.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare101Layout = new javax.swing.GroupLayout(gameSquare101);
        gameSquare101.setLayout(gameSquare101Layout);
        gameSquare101Layout.setHorizontalGroup(
            gameSquare101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare101Layout.setVerticalGroup(
            gameSquare101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare101, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        gameSquare102.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare102Layout = new javax.swing.GroupLayout(gameSquare102);
        gameSquare102.setLayout(gameSquare102Layout);
        gameSquare102Layout.setHorizontalGroup(
            gameSquare102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare102Layout.setVerticalGroup(
            gameSquare102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare102, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        gameSquare103.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare103Layout = new javax.swing.GroupLayout(gameSquare103);
        gameSquare103.setLayout(gameSquare103Layout);
        gameSquare103Layout.setHorizontalGroup(
            gameSquare103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare103Layout.setVerticalGroup(
            gameSquare103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare103, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        gameSquare104.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare104Layout = new javax.swing.GroupLayout(gameSquare104);
        gameSquare104.setLayout(gameSquare104Layout);
        gameSquare104Layout.setHorizontalGroup(
            gameSquare104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare104Layout.setVerticalGroup(
            gameSquare104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare104, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        gameSquare105.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare105Layout = new javax.swing.GroupLayout(gameSquare105);
        gameSquare105.setLayout(gameSquare105Layout);
        gameSquare105Layout.setHorizontalGroup(
            gameSquare105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare105Layout.setVerticalGroup(
            gameSquare105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare105, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        gameSquare106.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare106Layout = new javax.swing.GroupLayout(gameSquare106);
        gameSquare106.setLayout(gameSquare106Layout);
        gameSquare106Layout.setHorizontalGroup(
            gameSquare106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare106Layout.setVerticalGroup(
            gameSquare106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare106, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        gameSquare107.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare107Layout = new javax.swing.GroupLayout(gameSquare107);
        gameSquare107.setLayout(gameSquare107Layout);
        gameSquare107Layout.setHorizontalGroup(
            gameSquare107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare107Layout.setVerticalGroup(
            gameSquare107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare107, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        gameSquare108.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare108Layout = new javax.swing.GroupLayout(gameSquare108);
        gameSquare108.setLayout(gameSquare108Layout);
        gameSquare108Layout.setHorizontalGroup(
            gameSquare108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare108Layout.setVerticalGroup(
            gameSquare108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare108, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        gameSquare109.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare109Layout = new javax.swing.GroupLayout(gameSquare109);
        gameSquare109.setLayout(gameSquare109Layout);
        gameSquare109Layout.setHorizontalGroup(
            gameSquare109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare109Layout.setVerticalGroup(
            gameSquare109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare109, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        gameSquare110.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare110Layout = new javax.swing.GroupLayout(gameSquare110);
        gameSquare110.setLayout(gameSquare110Layout);
        gameSquare110Layout.setHorizontalGroup(
            gameSquare110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare110Layout.setVerticalGroup(
            gameSquare110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare110, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        gameSquare111.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare111Layout = new javax.swing.GroupLayout(gameSquare111);
        gameSquare111.setLayout(gameSquare111Layout);
        gameSquare111Layout.setHorizontalGroup(
            gameSquare111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare111Layout.setVerticalGroup(
            gameSquare111Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare111, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, -1, -1));

        gameSquare112.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare112Layout = new javax.swing.GroupLayout(gameSquare112);
        gameSquare112.setLayout(gameSquare112Layout);
        gameSquare112Layout.setHorizontalGroup(
            gameSquare112Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare112Layout.setVerticalGroup(
            gameSquare112Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare112, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        gameSquare113.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare113Layout = new javax.swing.GroupLayout(gameSquare113);
        gameSquare113.setLayout(gameSquare113Layout);
        gameSquare113Layout.setHorizontalGroup(
            gameSquare113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare113Layout.setVerticalGroup(
            gameSquare113Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare113, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        gameSquare15.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout gameSquare15Layout = new javax.swing.GroupLayout(gameSquare15);
        gameSquare15.setLayout(gameSquare15Layout);
        gameSquare15Layout.setHorizontalGroup(
            gameSquare15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        gameSquare15Layout.setVerticalGroup(
            gameSquare15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.add(gameSquare15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout gameSquare1Layout = new javax.swing.GroupLayout(gameSquare1);
        gameSquare1.setLayout(gameSquare1Layout);
        gameSquare1Layout.setHorizontalGroup(
            gameSquare1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        gameSquare1Layout.setVerticalGroup(
            gameSquare1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gameSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private stratego2.view.gui.GameSquare gameSquare1;
    private stratego2.view.gui.GameSquare gameSquare100;
    private stratego2.view.gui.GameSquare gameSquare101;
    private stratego2.view.gui.GameSquare gameSquare102;
    private stratego2.view.gui.GameSquare gameSquare103;
    private stratego2.view.gui.GameSquare gameSquare104;
    private stratego2.view.gui.GameSquare gameSquare105;
    private stratego2.view.gui.GameSquare gameSquare106;
    private stratego2.view.gui.GameSquare gameSquare107;
    private stratego2.view.gui.GameSquare gameSquare108;
    private stratego2.view.gui.GameSquare gameSquare109;
    private stratego2.view.gui.GameSquare gameSquare110;
    private stratego2.view.gui.GameSquare gameSquare111;
    private stratego2.view.gui.GameSquare gameSquare112;
    private stratego2.view.gui.GameSquare gameSquare113;
    private stratego2.view.gui.GameSquare gameSquare14;
    private stratego2.view.gui.GameSquare gameSquare15;
    private stratego2.view.gui.GameSquare gameSquare16;
    private stratego2.view.gui.GameSquare gameSquare17;
    private stratego2.view.gui.GameSquare gameSquare18;
    private stratego2.view.gui.GameSquare gameSquare19;
    private stratego2.view.gui.GameSquare gameSquare20;
    private stratego2.view.gui.GameSquare gameSquare21;
    private stratego2.view.gui.GameSquare gameSquare22;
    private stratego2.view.gui.GameSquare gameSquare23;
    private stratego2.view.gui.GameSquare gameSquare24;
    private stratego2.view.gui.GameSquare gameSquare25;
    private stratego2.view.gui.GameSquare gameSquare26;
    private stratego2.view.gui.GameSquare gameSquare27;
    private stratego2.view.gui.GameSquare gameSquare28;
    private stratego2.view.gui.GameSquare gameSquare29;
    private stratego2.view.gui.GameSquare gameSquare30;
    private stratego2.view.gui.GameSquare gameSquare31;
    private stratego2.view.gui.GameSquare gameSquare32;
    private stratego2.view.gui.GameSquare gameSquare33;
    private stratego2.view.gui.GameSquare gameSquare34;
    private stratego2.view.gui.GameSquare gameSquare35;
    private stratego2.view.gui.GameSquare gameSquare36;
    private stratego2.view.gui.GameSquare gameSquare37;
    private stratego2.view.gui.GameSquare gameSquare38;
    private stratego2.view.gui.GameSquare gameSquare39;
    private stratego2.view.gui.GameSquare gameSquare40;
    private stratego2.view.gui.GameSquare gameSquare41;
    private stratego2.view.gui.GameSquare gameSquare42;
    private stratego2.view.gui.GameSquare gameSquare43;
    private stratego2.view.gui.GameSquare gameSquare44;
    private stratego2.view.gui.GameSquare gameSquare45;
    private stratego2.view.gui.GameSquare gameSquare46;
    private stratego2.view.gui.GameSquare gameSquare47;
    private stratego2.view.gui.GameSquare gameSquare48;
    private stratego2.view.gui.GameSquare gameSquare49;
    private stratego2.view.gui.GameSquare gameSquare50;
    private stratego2.view.gui.GameSquare gameSquare51;
    private stratego2.view.gui.GameSquare gameSquare52;
    private stratego2.view.gui.GameSquare gameSquare53;
    private stratego2.view.gui.GameSquare gameSquare54;
    private stratego2.view.gui.GameSquare gameSquare55;
    private stratego2.view.gui.GameSquare gameSquare56;
    private stratego2.view.gui.GameSquare gameSquare57;
    private stratego2.view.gui.GameSquare gameSquare58;
    private stratego2.view.gui.GameSquare gameSquare59;
    private stratego2.view.gui.GameSquare gameSquare60;
    private stratego2.view.gui.GameSquare gameSquare61;
    private stratego2.view.gui.GameSquare gameSquare62;
    private stratego2.view.gui.GameSquare gameSquare63;
    private stratego2.view.gui.GameSquare gameSquare64;
    private stratego2.view.gui.GameSquare gameSquare65;
    private stratego2.view.gui.GameSquare gameSquare66;
    private stratego2.view.gui.GameSquare gameSquare67;
    private stratego2.view.gui.GameSquare gameSquare68;
    private stratego2.view.gui.GameSquare gameSquare69;
    private stratego2.view.gui.GameSquare gameSquare70;
    private stratego2.view.gui.GameSquare gameSquare71;
    private stratego2.view.gui.GameSquare gameSquare72;
    private stratego2.view.gui.GameSquare gameSquare73;
    private stratego2.view.gui.GameSquare gameSquare74;
    private stratego2.view.gui.GameSquare gameSquare75;
    private stratego2.view.gui.GameSquare gameSquare76;
    private stratego2.view.gui.GameSquare gameSquare77;
    private stratego2.view.gui.GameSquare gameSquare78;
    private stratego2.view.gui.GameSquare gameSquare79;
    private stratego2.view.gui.GameSquare gameSquare80;
    private stratego2.view.gui.GameSquare gameSquare81;
    private stratego2.view.gui.GameSquare gameSquare82;
    private stratego2.view.gui.GameSquare gameSquare83;
    private stratego2.view.gui.GameSquare gameSquare84;
    private stratego2.view.gui.GameSquare gameSquare85;
    private stratego2.view.gui.GameSquare gameSquare86;
    private stratego2.view.gui.GameSquare gameSquare87;
    private stratego2.view.gui.GameSquare gameSquare88;
    private stratego2.view.gui.GameSquare gameSquare89;
    private stratego2.view.gui.GameSquare gameSquare90;
    private stratego2.view.gui.GameSquare gameSquare91;
    private stratego2.view.gui.GameSquare gameSquare92;
    private stratego2.view.gui.GameSquare gameSquare93;
    private stratego2.view.gui.GameSquare gameSquare94;
    private stratego2.view.gui.GameSquare gameSquare95;
    private stratego2.view.gui.GameSquare gameSquare96;
    private stratego2.view.gui.GameSquare gameSquare97;
    private stratego2.view.gui.GameSquare gameSquare98;
    private stratego2.view.gui.GameSquare gameSquare99;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
